project:
  type: website

website:
  title: "A New Website, 2nd edition"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

publish:
  quarto_pub:
    type: quarto-pub
    site: a-new-website



